### ISSUE TITLE
Can not deploy sample

### ISSUE THREAD

**Issue by oscarcn1** [jbossdemocentral/brms-fuse-osgi-examples#1]
JBossFuse:karaf@root> features:addurl mvn:org.drools.example/features/1.0.0-SNAPSHOT/xml/features
JBossFuse:karaf@root> features:install simple-rule
Error executing command: URL [mvn:org.drools/drools-karaf-features/6.0.3-redhat-4/xml/features] could not be resolved.

**Comment by eschabell** [comment]
Assigning to our guru Christina, she will sort this out!

**Comment by oscarcn1** [comment]
it seems that you can not locate the repository because it is private

**Comment by eschabell** [comment]
which is sample that fails for you?

I have wiped out my maven repo, ran mvn clean install using only public facing connection / repos provided.... get this:

[INFO] Reactor Summary:
[INFO] 
[INFO] Drools OSGi Example :: Parent ...................... SUCCESS [  0.095 s]
[INFO] Drools OSGi Example :: Features Repository ......... SUCCESS [  0.005 s]
[INFO] Drools OSGi Example :: Simple rule ................. SUCCESS [  4.566 s]
[INFO] Drools OSGi Example :: Simple rule - using Declarative Service SUCCESS [  0.658 s]
[INFO] Drools OSGi Example :: Simple rule - using CDI Weld  SUCCESS [  0.007 s]
[INFO] Drools OSGi Example :: Simple XLS Decision Table rule SUCCESS [  0.008 s]
[INFO] Drools OSGi Example :: Fetch External Resource ..... SUCCESS [  0.008 s]
[INFO] Drools OSGi Example :: Simple kie-ci ............... SUCCESS [  0.008 s]
[INFO] Drools OSGI Example :: Kie Simple Project :: To be used with Kie-ci SUCCESS [  0.003 s]
[INFO] Drools OSGI Example :: Assets Bundle ............... SUCCESS [  0.005 s]
[INFO] Drools OSGi Example :: Simple rule imported from Bundle SUCCESS [  0.010 s]
[INFO] Drools OSGi Example :: Kie Blueprint, Drools, Camel Example SUCCESS [  2.425 s]
[INFO] jBPM OSGi Example :: Simple Process ................ SUCCESS [  0.010 s]
[INFO] Spring & jBPM :: OSGI Example ...................... SUCCESS [  0.009 s]
[INFO] Spring & jBPM Persistent :: OSGI Example ........... SUCCESS [  0.008 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by oscarcn1** [comment]
Yes build works but deploy does not work :(

JBossFuse:karaf@root> features:addurl mvn:org.drools.example/features/1.0.0-SNAPSHOT/xml/features
JBossFuse:karaf@root> features:install simple-rule
Error executing command: URL [mvn:org.drools/drools-karaf-features/6.0.3-redhat-4/xml/features] could not be resolved.

**Comment by oscarcn1** [comment]
There is a previous phase to build the project, you need to install bpms-brms-6.0.2.GA-redhat-5-maven-repository.zip into your maven repository, after that the example works fine

**Comment by eschabell** [comment]
This does need to be updated to BPM Suite 6.1, it currently also is available in public facing maven repos so needs to be adjusted to pull deps from there.... not require a downloaded repo.

**Comment by niteshjain132** [comment]
i'm facing the same issue, https://github.com/cmoulliard/droolsjbpm-osgi-examples , maven build is successful, but i'm not able to install any of the features

JBossFuse:karaf@root> features:install drools-decisiontable-kie-spring-camel
Error executing command: URL [mvn:org.drools/drools-karaf-features/6.0.3-redhat-4/xml/features] could not be resolved.

can you please share the link to download "bpms-brms-6.0.2.GA-redhat-5-maven-repository.zip"

**Comment by weimeilin79** [comment]
I fixed it. The problem was because this project was base on a pre-released version of BRMS. And the dependencies has changed since. I updated to the current 6.2.0 release of BRMS. Then it worked.
